# Generated by Django 3.0.8 on 2020-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_post_hashtag_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag_field',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
