# Generated by Django 3.1 on 2020-11-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
